/*
 * HFC Market Intelligence — source data
 * ------------------------------------------------------------------
 * Generated from templates/HFC_market_intelligence_template.xlsx by tools/sync_data_js.py.
 * Market growth is Oxford Economics data (construction work done); addressable market,
 * HFC figures and qualitative scores are ILLUSTRATIVE. Update the Excel template and
 * upload it on the dashboard page, or regenerate this file from it.
 *
 * One row = one country x one end market.
 *   segment: "Residential" or "Non-residential" (non-residential includes multi-residential)
 *
 * All growth figures and market shares are in % (3.2 means 3.2 %).
 *   market_size            HFC addressable market, last year (base year, e.g. 2025), EUR m
 *   hfc_sales              HFC sales, last year (base year), EUR m. Optional: if empty, market_size x ms_py
 *   mkt_cagr_hist          Market CAGR, last 5 years
 *   mkt_growth_cy          Market growth, current year (estimate)
 *   mkt_cagr_fwd           Market CAGR projection, next 5 years
 *   hfc_cagr_hist          HFC sales CAGR, last 5 years
 *   hfc_growth_cy          HFC projected growth, current year
 *   hfc_cagr_bp            HFC business-plan CAGR, next 5 years
 *   ms_cy                  HFC market share, current year
 *   ms_py                  HFC market share, last year
 *
 * Market split by construction type (market growth = construction work done, Oxford Economics):
 *   reno_share             Renovation share of the market, % (the rest is new build)
 *   mkt_reno_cagr_hist     Renovation CAGR, last 5 years
 *   mkt_reno_growth_cy     Renovation growth, current year
 *   mkt_reno_cagr_fwd      Renovation CAGR projection, next 5 years
 *   mkt_nb_cagr_hist       New build CAGR, last 5 years
 *   mkt_nb_growth_cy       New build growth, current year
 *   mkt_nb_cagr_fwd        New build CAGR projection, next 5 years
 *
 * Qualitative scores for the attractiveness / ability-to-win matrix, 1 (weak) to 5 (strong):
 *   profitability          Price level and margin potential of the market
 *   competitive_intensity  5 = benign competition, 1 = very fierce
 *   channel_access         HFC access to distributors, installers, specifiers
 *   product_fit            Fit of the HFC range with local norms and demand
 */
window.HFC_CONFIG = {
  company: "HFC",
  currentYear: 2026,
  currency: "EUR m",
  // Weights used to build the two matrix axes (they are normalised, so any scale works).
  weights: {
    attractiveness: { market_size: 30, reno_growth: 15, nb_growth: 15, profitability: 20, competitive_intensity: 20 },
    ability: { market_share: 45, channel_access: 30, product_fit: 25 }
  },
  // Diagonal zone lines on the matrix: a country's zone is set by attractiveness + ability to win (each 1-5, so 2-10).
  zones: { leadership: 7, priority_growth: 5.5 }
};

window.HFC_DATA = [
  // generated by tools/sync_data_js.py from HFC_market_intelligence_template.xlsx (country, code, segment, market_size, hfc_sales, mkt_cagr_hist, mkt_growth_cy, mkt_cagr_fwd, hfc_cagr_hist, hfc_growth_cy, hfc_cagr_bp, ms_cy, ms_py, profitability, competitive_intensity, channel_access, product_fit, reno_share, mkt_reno_cagr_hist, mkt_reno_growth_cy, mkt_reno_cagr_fwd, mkt_nb_cagr_hist, mkt_nb_growth_cy, mkt_nb_cagr_fwd)
  ["Poland", "PL", "Residential", 115.0, 5.8, null, 6.54, 2.25, 9.0, 8.5, 10.0, 5.14, 5.04, 3, 3, 2, 4, null, null, null, null, null, null, null],
  ["Poland", "PL", "Non-residential", 260.0, 9.9, null, 5.97, 2.35, 9.5, 9.0, 10.5, 3.92, 3.81, 3, 3, 2, 4, null, null, null, null, null, null, null],
  ["Czech Republic", "CZ", "Residential", 65.0, 3.9, null, -1.68, 2.19, 6.0, 5.0, 7.0, 6.41, 6.0, 3, 3, 3, 3, null, null, null, null, null, null, null],
  ["Czech Republic", "CZ", "Non-residential", 85.0, 3.4, null, 5.11, 4.0, 6.5, 5.5, 7.5, 4.01, 4.0, 3, 3, 3, 3, null, null, null, null, null, null, null],
  ["Hungary", "HU", "Residential", 20.0, 0.8, null, 8.69, 0.65, 5.0, 3.0, 6.0, 3.79, 4.0, 2, 3, 2, 3, null, null, null, null, null, null, null],
  ["Hungary", "HU", "Non-residential", 40.0, 1.2, null, 11.67, 2.69, 5.5, 3.5, 6.5, 2.78, 3.0, 2, 3, 2, 3, null, null, null, null, null, null, null],
  ["Netherlands", "NL", "Residential", 320.0, 51.2, null, 1.32, 2.9, 3.5, 2.0, 3.0, 16.11, 16.0, 4, 3, 5, 4, null, null, null, null, null, null, null],
  ["Netherlands", "NL", "Non-residential", 270.0, 36.5, null, 2.68, 2.89, 4.0, 2.5, 3.5, 13.5, 13.52, 4, 3, 5, 4, null, null, null, null, null, null, null],
  ["Sweden", "SE", "Residential", 90.0, 6.3, null, 2.05, 2.57, 1.0, 0.0, 3.5, 6.86, 7.0, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Sweden", "SE", "Non-residential", 185.0, 10.2, null, -0.65, 2.27, 1.5, 0.5, 4.0, 5.58, 5.51, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Norway", "NO", "Residential", 50.0, 3.8, null, -5.56, 2.86, 1.5, 0.5, 3.0, 8.09, 7.6, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Norway", "NO", "Non-residential", 130.0, 7.2, null, 2.43, 2.23, 2.0, 1.0, 3.5, 5.46, 5.54, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Finland", "FI", "Residential", 20.0, 1.3, null, -2.97, 4.11, 0.5, -0.5, 3.0, 6.67, 6.5, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Finland", "FI", "Non-residential", 50.0, 2.5, null, -0.85, 3.31, 1.0, 0.0, 3.5, 5.04, 5.0, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Denmark", "DK", "Residential", 135.0, 10.8, null, -5.3, 1.82, 2.0, 1.0, 3.0, 8.53, 8.0, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Denmark", "DK", "Non-residential", 90.0, 5.4, null, -4.08, 2.16, 2.5, 1.5, 3.5, 6.35, 6.0, 4, 3, 3, 3, null, null, null, null, null, null, null],
  ["Germany", "DE", "Residential", 1060.0, 63.6, null, -0.57, 2.87, 2.0, -2.0, 3.0, 5.91, 6.0, 3, 2, 3, 3, null, null, null, null, null, null, null],
  ["Germany", "DE", "Non-residential", 1195.0, 53.8, null, 2.37, 3.73, 2.5, -1.5, 3.5, 4.33, 4.5, 3, 2, 3, 3, null, null, null, null, null, null, null],
  ["Austria", "AT", "Residential", 85.0, 6.0, null, 2.5, 3.74, 2.0, -1.0, 2.5, 6.82, 7.06, 4, 3, 3, 4, null, null, null, null, null, null, null],
  ["Austria", "AT", "Non-residential", 240.0, 12.0, null, 3.19, 2.57, 2.5, -0.5, 3.0, 4.82, 5.0, 4, 3, 3, 4, null, null, null, null, null, null, null],
  ["Switzerland", "CH", "Residential", 75.0, 9.0, null, -0.78, 1.44, 2.5, 1.5, 2.0, 12.28, 12.0, 5, 4, 4, 4, null, null, null, null, null, null, null],
  ["Switzerland", "CH", "Non-residential", 370.0, 37.0, null, 2.24, 2.87, 3.0, 2.0, 2.5, 9.98, 10.0, 5, 4, 4, 4, null, null, null, null, null, null, null],
  ["United Kingdom", "UK", "Residential", 1005.0, 32.2, null, 0.97, 4.23, -1.0, 1.5, 2.5, 3.22, 3.2, 3, 2, 2, 3, null, null, null, null, null, null, null],
  ["United Kingdom", "UK", "Non-residential", 760.0, 21.3, null, -0.54, 4.03, -0.5, 2.0, 3.0, 2.87, 2.8, 3, 2, 2, 3, null, null, null, null, null, null, null],
  ["France", "FR", "Residential", 525.0, 94.5, null, 0.41, 1.92, 4.0, 1.0, 3.5, 18.11, 18.0, 4, 3, 4, 4, null, null, null, null, null, null, null],
  ["France", "FR", "Non-residential", 1025.0, 143.5, null, 1.04, 1.22, 4.5, 1.5, 4.0, 14.06, 14.0, 4, 3, 4, 4, null, null, null, null, null, null, null],
  ["Italy", "IT", "Residential", 300.0, 33.0, null, -2.82, -2.24, 3.0, -3.0, 2.0, 10.98, 11.0, 3, 3, 4, 3, null, null, null, null, null, null, null],
  ["Italy", "IT", "Non-residential", 1030.0, 97.8, null, 0.17, 1.41, 3.5, -2.5, 2.5, 9.24, 9.5, 3, 3, 4, 3, null, null, null, null, null, null, null],
  ["Belgium", "BE", "Residential", 115.0, 17.2, null, -3.01, 2.29, 3.0, 2.0, 3.5, 15.73, 14.96, 4, 3, 4, 4, null, null, null, null, null, null, null],
  ["Belgium", "BE", "Non-residential", 215.0, 25.8, null, 1.81, 3.06, 3.5, 2.5, 4.0, 12.08, 12.0, 4, 3, 4, 4, null, null, null, null, null, null, null],
  ["Spain", "ES", "Residential", 215.0, 21.1, null, 1.77, 2.32, 7.5, 6.0, 8.0, 10.22, 9.81, 3, 3, 3, 4, null, null, null, null, null, null, null],
  ["Spain", "ES", "Non-residential", 945.0, 70.9, null, 6.68, 3.66, 8.0, 6.5, 8.5, 7.49, 7.5, 3, 3, 3, 4, null, null, null, null, null, null, null],
  ["Portugal", "PT", "Residential", 45.0, 3.6, null, 4.23, 0.19, 6.5, 5.0, 5.0, 8.06, 8.0, 3, 3, 3, 4, null, null, null, null, null, null, null],
  ["Portugal", "PT", "Non-residential", 95.0, 5.7, null, 8.46, 2.75, 7.0, 5.5, 5.5, 5.84, 6.0, 3, 3, 3, 4, null, null, null, null, null, null, null]
];
