/*
 * HFC Market Intelligence — source data
 * ------------------------------------------------------------------
 * Generated from templates/HFC_market_intelligence_template.xlsx by tools/sync_data_js.py.
 * Market growth is Oxford Economics data (construction work done); addressable market,
 * HFC figures and qualitative scores are ILLUSTRATIVE. Update the Excel template and
 * upload it on the dashboard page, or regenerate this file from it.
 *
 * One row = one country x one end market.
 *   segment: "Residential" or "Commercial" (commercial + multi-family residential)
 *
 * All growth figures and market shares are in % (3.2 means 3.2 %).
 *   market_size            HFC addressable market, last year (base year, e.g. 2025), EUR m
 *   hfc_sales              HFC sales, last year (base year), EUR m. Optional: if empty, market_size x ms_py
 *   mkt_cagr_hist          Market CAGR, last 5 years
 *   mkt_growth_cy          Market growth, current year (estimate)
 *   mkt_cagr_fwd           Market CAGR projection, next 5 years
 *   hfc_cagr_hist          HFC sales CAGR, last 5 years
 *   hfc_growth_cy          HFC projected growth, current year
 *   hfc_cagr_bp            HFC business-plan CAGR, next 5 years
 *   ms_cy                  HFC market share, current year
 *   ms_py                  HFC market share, last year
 *
 * Market split by construction type (market growth = construction work done, Oxford Economics):
 *   reno_share             Renovation share of the market, % (the rest is new build)
 *   mkt_reno_cagr_hist     Renovation CAGR, last 5 years
 *   mkt_reno_growth_cy     Renovation growth, current year
 *   mkt_reno_cagr_fwd      Renovation CAGR projection, next 5 years
 *   mkt_nb_cagr_hist       New build CAGR, last 5 years
 *   mkt_nb_growth_cy       New build growth, current year
 *   mkt_nb_cagr_fwd        New build CAGR projection, next 5 years
 *
 * Qualitative scores for the attractiveness / ability-to-win matrix, 1 (weak) to 5 (strong):
 *   profitability          Price level and margin potential of the market
 *   competitive_intensity  5 = benign competition, 1 = very fierce
 *   channel_access         HFC access to distributors, installers, specifiers
 *   product_fit            Fit of the HFC range with local norms and demand
 */
window.HFC_CONFIG = {
  company: "HFC",
  currentYear: 2026,
  currency: "EUR m",
  // Weights used to build the two matrix axes (they are normalised, so any scale works).
  weights: {
    attractiveness: { market_size: 30, reno_growth: 15, nb_growth: 15, profitability: 20, competitive_intensity: 20 },
    ability: { market_share: 45, channel_access: 30, product_fit: 25 }
  },
  // Diagonal zone lines on the matrix: a country's zone is set by attractiveness + ability to win (each 1-5, so 2-10).
  zones: { leadership: 7, priority_growth: 5.5 }
};

window.HFC_DATA = [
  // generated by tools/sync_data_js.py from HFC_market_intelligence_template.xlsx (country, code, segment, market_size, hfc_sales, mkt_cagr_hist, mkt_growth_cy, mkt_cagr_fwd, hfc_cagr_hist, hfc_growth_cy, hfc_cagr_bp, ms_cy, ms_py, profitability, competitive_intensity, channel_access, product_fit, reno_share, mkt_reno_cagr_hist, mkt_reno_growth_cy, mkt_reno_cagr_fwd, mkt_nb_cagr_hist, mkt_nb_growth_cy, mkt_nb_cagr_fwd)
  ["Poland", "PL", "Residential", 115.0, 5.8, -1.96, 6.54, 2.25, 9.0, 8.5, 10.0, 5.14, 5.04, 3, 3, 2, 4, 53.26, 2.11, 18.59, 1.42, -5.62, -7.18, 3.42],
  ["Poland", "PL", "Commercial", 260.0, 9.9, 0.34, 5.97, 2.35, 9.5, 9.0, 10.5, 3.92, 3.81, 3, 3, 2, 4, 32.7, 0.99, 16.51, 2.05, 0.03, 0.84, 2.51],
  ["Czech Republic", "CZ", "Residential", 65.0, 3.9, -2.41, -1.68, 2.19, 6.0, 5.0, 7.0, 6.41, 6.0, 3, 3, 3, 3, 32.34, 3.19, -9.43, 3.11, -4.53, 2.02, 1.79],
  ["Czech Republic", "CZ", "Commercial", 85.0, 3.4, -0.34, 5.12, 4.0, 6.5, 5.5, 7.5, 4.01, 4.0, 3, 3, 3, 3, 31.82, -0.02, 3.57, 5.42, -0.48, 5.84, 3.33],
  ["Hungary", "HU", "Residential", 20.0, 0.8, -0.33, 8.69, 0.65, 5.0, 3.0, 6.0, 3.79, 4.0, 2, 3, 2, 3, 53.02, 2.64, -1.69, 5.28, -3.15, 20.41, -4.55],
  ["Hungary", "HU", "Commercial", 40.0, 1.2, 0.84, 11.67, 2.69, 5.5, 3.5, 6.5, 2.78, 3.0, 2, 3, 2, 3, 49.52, 4.31, 13.73, 0.75, -1.98, 9.65, 4.52],
  ["Netherlands", "NL", "Residential", 320.0, 51.2, 1.63, 1.32, 2.9, 3.5, 2.0, 3.0, 16.11, 16.0, 4, 3, 5, 4, 61.34, 3.88, 0.34, 3.5, -1.41, 2.86, 1.95],
  ["Netherlands", "NL", "Commercial", 270.0, 36.5, 2.42, 2.68, 2.89, 4.0, 2.5, 3.5, 13.5, 13.52, 4, 3, 5, 4, 42.99, 0.69, 2.53, 3.79, 3.84, 2.79, 2.19],
  ["Sweden", "SE", "Residential", 90.0, 6.3, -0.04, 2.05, 2.57, 1.0, 0.0, 3.5, 6.86, 7.0, 4, 3, 3, 3, 60.68, 4.6, -0.48, 2.66, -5.34, 5.97, 2.44],
  ["Sweden", "SE", "Commercial", 185.0, 10.2, -0.4, -0.65, 2.27, 1.5, 0.5, 4.0, 5.58, 5.51, 4, 3, 3, 3, 54.1, 5.02, -2.39, 2.66, -5.12, 1.4, 1.82],
  ["Norway", "NO", "Residential", 50.0, 3.8, -2.45, -5.56, 2.86, 1.5, 0.5, 3.0, 8.09, 7.6, 4, 3, 3, 3, 75.23, 0.92, -5.99, 2.13, -9.73, -4.26, 4.94],
  ["Norway", "NO", "Commercial", 130.0, 7.2, -1.37, 2.43, 2.23, 2.0, 1.0, 3.5, 5.46, 5.54, 4, 3, 3, 3, 59.16, 1.53, -0.6, 3.14, -4.83, 6.83, 0.96],
  ["Finland", "FI", "Residential", 20.0, 1.3, -6.24, -2.97, 4.11, 0.5, -0.5, 3.0, 6.67, 6.5, 4, 3, 3, 3, 80.02, -4.02, -1.63, 3.79, -12.88, -8.33, 5.41],
  ["Finland", "FI", "Commercial", 50.0, 2.5, -6.27, -0.85, 3.31, 1.0, 0.0, 3.5, 5.04, 5.0, 4, 3, 3, 3, 62.58, -1.94, 2.97, 2.97, -11.58, -7.24, 3.93],
  ["Denmark", "DK", "Residential", 135.0, 10.8, 3.26, -5.3, 1.82, 2.0, 1.0, 3.0, 8.53, 8.0, 4, 3, 3, 3, 81.69, 5.82, -5.06, 2.82, -4.96, -6.37, -3.29],
  ["Denmark", "DK", "Commercial", 90.0, 5.4, 3.54, -4.08, 2.16, 2.5, 1.5, 3.5, 6.35, 6.0, 4, 3, 3, 3, 45.07, 6.82, -3.51, 2.87, 1.25, -4.55, 1.55],
  ["Germany", "DE", "Residential", 1060.0, 63.6, -5.34, -0.57, 2.87, 2.0, -2.0, 3.0, 5.91, 6.0, 3, 2, 3, 3, 82.47, -3.08, -2.3, 2.97, -12.98, 7.57, 2.44],
  ["Germany", "DE", "Commercial", 1195.0, 53.8, -5.19, 2.37, 3.73, 2.5, -1.5, 3.5, 4.33, 4.5, 3, 2, 3, 3, 63.45, -4.41, 2.0, 4.13, -6.47, 3.01, 3.01],
  ["Austria", "AT", "Residential", 85.0, 6.0, -4.03, 2.5, 3.74, 2.0, -1.0, 2.5, 6.82, 7.06, 4, 3, 3, 4, 42.24, -1.2, 0.75, 3.63, -5.83, 3.78, 3.81],
  ["Austria", "AT", "Commercial", 240.0, 12.0, -4.99, 3.19, 2.57, 2.5, -0.5, 3.0, 4.82, 5.0, 4, 3, 3, 4, 36.59, -0.56, 11.34, 2.11, -7.08, -1.51, 2.87],
  ["Switzerland", "CH", "Residential", 75.0, 9.0, 0.03, -0.78, 1.44, 2.5, 1.5, 2.0, 12.28, 12.0, 5, 4, 4, 4, 43.39, -0.55, 2.67, 3.63, 0.49, -3.43, -0.5],
  ["Switzerland", "CH", "Commercial", 370.0, 37.0, -0.2, 2.24, 2.87, 3.0, 2.0, 2.5, 9.98, 10.0, 5, 4, 4, 4, 34.71, 1.37, -2.2, 0.92, -0.98, 4.6, 3.79],
  ["United Kingdom", "UK", "Residential", 1005.0, 32.2, 4.85, 0.97, 4.23, -1.0, 1.5, 2.5, 3.22, 3.2, 3, 2, 2, 3, 47.64, 7.81, -2.92, 3.48, 2.53, 4.5, 4.86],
  ["United Kingdom", "UK", "Commercial", 760.0, 21.3, 0.48, -0.54, 4.03, -0.5, 2.0, 3.0, 2.87, 2.8, 3, 2, 2, 3, 40.77, 5.33, -0.08, 5.39, -2.2, -0.85, 3.05],
  ["France", "FR", "Residential", 525.0, 94.5, -1.55, 0.41, 1.92, 4.0, 1.0, 3.5, 18.11, 18.0, 4, 3, 4, 4, 77.49, 2.81, 1.76, 1.93, -11.15, -4.25, 1.89],
  ["France", "FR", "Commercial", 1025.0, 143.5, 0.74, 1.04, 1.22, 4.5, 1.5, 4.0, 14.06, 14.0, 4, 3, 4, 4, 63.43, 4.46, 1.64, 1.69, -4.23, 0.0, 0.36],
  ["Italy", "IT", "Residential", 300.0, 33.0, 10.51, -2.82, -2.24, 3.0, -3.0, 2.0, 10.98, 11.0, 3, 3, 4, 3, 79.15, 10.76, -4.14, -1.27, 9.58, 2.18, -6.06],
  ["Italy", "IT", "Commercial", 1030.0, 97.8, 9.58, 0.17, 1.41, 3.5, -2.5, 2.5, 9.24, 9.5, 3, 3, 4, 3, 82.77, 9.74, -0.09, 1.22, 8.8, 1.44, 2.28],
  ["Belgium", "BE", "Residential", 115.0, 17.2, 0.56, -3.01, 2.29, 3.0, 2.0, 3.5, 15.73, 14.96, 4, 3, 4, 4, 73.49, 3.08, -1.12, 2.22, -4.91, -8.24, 2.48],
  ["Belgium", "BE", "Commercial", 215.0, 25.8, 2.59, 1.81, 3.06, 3.5, 2.5, 4.0, 12.08, 12.0, 4, 3, 4, 4, 58.69, 3.87, 1.87, 3.78, 0.93, 1.73, 2.01],
  ["Spain", "ES", "Residential", 215.0, 21.1, 3.26, 1.77, 2.32, 7.5, 6.0, 8.0, 10.22, 9.81, 3, 3, 3, 4, 37.04, 1.75, -3.01, 2.95, 4.22, 4.58, 1.98],
  ["Spain", "ES", "Commercial", 945.0, 70.9, 4.67, 6.68, 3.66, 8.0, 6.5, 8.5, 7.49, 7.5, 3, 3, 3, 4, 35.85, 5.06, -0.13, 4.07, 4.46, 10.48, 3.44],
  ["Portugal", "PT", "Residential", 45.0, 3.6, 3.02, 4.23, 0.19, 6.5, 5.0, 5.0, 8.06, 8.0, 3, 3, 3, 4, 79.57, 7.67, 3.11, -0.23, -8.12, 8.56, 1.71],
  ["Portugal", "PT", "Commercial", 95.0, 5.7, 3.74, 8.46, 2.75, 7.0, 5.5, 5.5, 5.84, 6.0, 3, 3, 3, 4, 54.04, 1.62, 8.76, 3.12, 6.63, 8.1, 2.32]
];
