"""Refresh the default dashboard data (dashboard/data.js) from the recalculated Excel template.

Usage:  python3 tools/sync_data_js.py [templates/HFC_market_intelligence_template.xlsx]
Reads the cached values of the 'Dashboard data' and 'Settings' sheets, so recalculate the workbook first.
"""
import json
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "templates" / "HFC_market_intelligence_template.xlsx"
DATA_JS = ROOT / "dashboard" / "data.js"
FIELDS = ["country", "code", "segment", "market_size", "hfc_sales", "mkt_cagr_hist", "mkt_growth_cy", "mkt_cagr_fwd",
          "hfc_cagr_hist", "hfc_growth_cy", "hfc_cagr_bp", "ms_cy", "ms_py",
          "profitability", "competitive_intensity", "channel_access", "product_fit",
          "reno_share", "mkt_reno_cagr_hist", "mkt_reno_growth_cy", "mkt_reno_cagr_fwd", "mkt_nb_cagr_hist", "mkt_nb_growth_cy", "mkt_nb_cagr_fwd"]

wb = load_workbook(SRC, data_only=True)
ws = wb["Dashboard data"]
grid = [list(r) for r in ws.iter_rows(values_only=True)]
hi = next(i for i, r in enumerate(grid) if "country" in r and "market_size" in r)
idx = {k: grid[hi].index(k) for k in FIELDS}
rows = []
for r in grid[hi + 1:]:
    if not r[idx["country"]]:
        continue
    out = []
    for k in FIELDS:
        v = r[idx[k]]
        if v in ("", None):
            out.append(None)
        elif isinstance(v, (int, float)):
            out.append(round(float(v), 2) if k not in ("profitability", "competitive_intensity", "channel_access", "product_fit") else int(v))
        else:
            out.append(str(v))
    rows.append(out)
if not rows:
    sys.exit("No rows with values: recalculate the workbook first.")

def cell(v):
    return "null" if v is None else json.dumps(v)

text = DATA_JS.read_text()
start = text.index("window.HFC_DATA = [")
body = ["window.HFC_DATA = [",
        "  // generated by tools/sync_data_js.py from " + SRC.name + " (" + ", ".join(FIELDS) + ")"]
body += ["  [" + ", ".join(cell(v) for v in row) + "]" + ("," if i < len(rows) - 1 else "") for i, row in enumerate(rows)]
body.append("];")
DATA_JS.write_text(text[:start] + "\n".join(body) + "\n")
print(f"{len(rows)} rows written to {DATA_JS}")
